#!/bin/bash

if [ "$1" = "debug" ] || [ "$1" = "run" ]
then
    ti="-ti"
fi

docker run \
  -e NEWT_USER=$(id -u) \
  -e NEWT_GROUP=$(id -g) \
  -e NEWT_HOST=$(uname) \
  $ti --rm --device=/dev/bus/usb \
  --privileged \
  -v $(pwd):/workspace \
  -w /workspace \
  mynewt/newt:1.7.0-6 /newt "$@"
